#!/bin/bash

#
# Backup and restore script for Crowbar
#
# 2013-2014, SUSE Linux Products GmbH
# Authors: {bwiedemann,jdsn}@suse.de
#

BFILES="etc/chef tftpboot/validation.pem var/lib/couchdb/chef.couch etc/crowbar"

function backup()
{
  /etc/cron.daily/chef-couchdb-cleanup >/dev/null 2>&1 # to get smaller backups
  cd /
  echo "backing up to $FILE..."
  tar -czf "$FILE" $BFILES
}

# to be used on an already deployed crowbar
function cleanup()
{
  cd /
  for service in crowbar chef-{server,solr,expander,client} couchdb apache2 named dhcpd xinetd rabbitmq-server ; do
    /etc/init.d/$service stop
  done
  killall epmd # part of rabbitmq
  killall looper_chef_client.sh
  LOGS=var/log/{crowbar,chef,couchdb,apache2}
  DEPLOYED="var/lib/chef etc/bind etc/dhcp3 etc/xinetd.d/tftp /srv/tftpboot/discovery/pxelinux.cfg/*"
  rm -rf $BFILES $LOGS $DEPLOYED
}

function purge()
{
  cleanup
  zypper -n rm `rpm -qa|grep -e crowbar -e chef -e rubygem -e susecloud` couchdb createrepo erlang rabbitmq-server sleshammer yum-common bind bind-chrootenv dhcp-server tftp
  rm -rf /opt/dell /var/log/{rabbitmq,nodes,crowbar,couchdb,chef,barclamps} /var/lib/{chef,couchdb,crowbar,dhcp,named,rabbitmq} /var/cache/chef /var/run/{chef,crowbar,named,rabbitmq} /var/chef /etc/sysconfig/{dhcpd,named,rabbitmq-server} /etc/{bind,chef,dhcp3,crowbar}
  echo "you need to manually restore /etc/resolv.conf"
}

function restore_files()
{
  cd /
  echo "restoring from $FILE..."
  tar -xf "$FILE"
}

function restore()
{
  restore_files
  install-suse-cloud --verbose
  rccouchdb stop
  restore_files
  rccouchdb start
  rcchef-server restart
  chef-client
}

function help()
{
  echo "usage: $0 [help|backup|restore] <FILE>"
  echo
  echo " backup <FILE>"
  echo "     create a backup tarball of admin node config data in <FILE>"
  echo " restore <FILE>"
  echo "     restore a backup of an admin node config from tarball <FILE>"
}

FILE=${2:-/tmp/backup-crowbar.tar.gz}

$@
